-- Active: 1657307972966@@127.0.0.1@3306

USE Caronapp;

DROP TABLE IF EXISTS `USUARIO`;

CREATE TABLE `USUARIO` (
	`id` INT unsigned NOT NULL AUTO_INCREMENT,
	`cpf` VARCHAR(20) NOT NULL,
    `nome` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `sexo` VARCHAR(1) NOT NULL,
	`telefone` VARCHAR(14) NOT NULL,
	`senha` VARCHAR(200) NOT NULL,
	`cnh` VARCHAR(30),
	`foto` MEDIUMBLOB,
	`nota` DOUBLE unsigned NOT NULL DEFAULT '5',
	`num_avaliacoes` INT unsigned DEFAULT '0',
	PRIMARY KEY (`id`)
);



DROP TABLE IF EXISTS `CARONA`;

CREATE TABLE `CARONA` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`valor` DOUBLE NOT NULL,
	`origem` INT NOT NULL,
	`destino` INT NOT NULL,
	`veiculocarona` INT NOT NULL,
	`espaco` INT NOT NULL,
	`obs` TEXT(500),
	`datainicio` DATETIME NOT NULL,
	`datafim` DATETIME ,
	`grupo` INT,
    `condutor` INT NOT NULL,
	PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `CARONA_USUARIO`;

CREATE TABLE `CARONA_USUARIO` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `carona_id` INT NOT NULL,
    `usuario_id` INT NOT NULL,
    `tipo` VARCHAR(10)  ,
    PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `CARONA_USUARIO_AVALICAO`;

CREATE TABLE `CARONA_USUARIO_AVALICAO`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `carona_usuario_id` INT NOT NULL,
    `nota` DOUBLE NOT NULL,
    `comentario` TEXT(500),
    PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `GRUPO`;

CREATE TABLE GRUPO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(50) NOT NULL,
    `codigo` TEXT(500),
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `GRUPO_USUARIO`;

CREATE TABLE GRUPO_USUARIO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `grupo_id` INT NOT NULL,
    `usuario_id` INT NOT NULL,
    PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `LOCALIZACAO`;

CREATE TABLE LOCALIZACAO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `local` VARCHAR(100) NOT NULL,
    `cidade` INT NOT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `CIDADE`;

CREATE TABLE CIDADE( 
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(50) NOT NULL,
    `uf` INT NOT NULL,
    PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `ESTADO`;

CREATE TABLE ESTADO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `nome` VARCHAR(50) NOT NULL,
    `sigla` VARCHAR(2) NOT NULL,
    PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `VEICULO`;
CREATE TABLE VEICULO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `marca` VARCHAR(50) NOT NULL,
    `nome` VARCHAR(50) NOT NULL,
    `tipo` VARCHAR(50) ,
    `capacidade` INT NOT NULL,
    `foto` MEDIUMBLOB,
    PRIMARY KEY (`id`)
);



DROP TABLE IF EXISTS `VEICULO_USUARIO`;

CREATE TABLE VEICULO_USUARIO(
    `id` INT NOT NULL AUTO_INCREMENT,
    `veiculo` INT NOT NULL,
	`ano` VARCHAR(4) NOT NULL,
    `cor` VARCHAR(15) NOT NULL,
    `placa` VARCHAR(7) NOT NULL,
    `renavam` VARCHAR(30) NOT NULL,
    `usuario_id` INT unsigned NOT NULL,
    
    FOREIGN KEY (`usuario_id`) REFERENCES `USUARIO`(`id`) ON DELETE CASCADE,

    FOREIGN KEY (`veiculo`) REFERENCES `VEICULO`(`id`) ON DELETE CASCADE,

    PRIMARY KEY (`id`)
);


DROP TABLE IF EXISTS `VEICULO_CARONA`;

CREATE TABLE `VEICULO_CARONA` (
	`id` INT NOT NULL AUTO_INCREMENT,
    `veiculo` INT NOT NULL,
	`ano` VARCHAR(4) NOT NULL,
	`cor` VARCHAR(15) NOT NULL,
	`placa` VARCHAR(7) NOT NULL,
	`renavam` VARCHAR(30) NOT NULL,
    

    FOREIGN KEY (`veiculo`) REFERENCES `VEICULO`(`id`) ON DELETE CASCADE,
    PRIMARY KEY (`id`)
);


